### ISSUE TITLE
Improve Container API

### ISSUE THREAD

**Issue by yachaka** [edvinerikson/relay-subscriptions#20]
Hi,

First off, great work. It looks nice.
I was wondering when looking at the Container API, is there any reason the `subscriptions`  field on the `createContainer` method doesn't return an object which gets mapped to `this.props` ?
The subscriptions would still be auto-fired/auto-stopped, but you could also unsubscribe from them at any time using `this.props.subscriptionName.dispose()`.

You would also be able to inspect any field you would have returned in the `sendSubscription` method of the `NetworkLayer`, e.g. the underlying `socket.io` request providing useful information like the connection status.

To illustrate :

``` js

const MyComponent = ({ postCommentsSubscription }) => { /* Do something */ }

const MyContainer = RelaySubscriptions.createContainer(MyComponent, {
    fragments: {
        post: () => /* ... */
    },

    subscriptions: (props) => ({
        postCommentsSubscription: new PostCommentsSubscription({ postID: props.post.id }),
    }),
})
```

Aside from this, do you have any information on if and when this repo will be merged into relay official repo ? It would make sense !

**Comment by edvinerikson** [comment]
Hi and thanks for the proposal.

I think that this is already doable with the current imperative API.

The declarative container API is not intended to solve all use-cases only the most common. If you want more advanced control you should use the [imperative API](https://github.com/edvinerikson/relay-subscriptions/blob/master/docs/API.md#subscribe-1) instead which gives you more fine grained control of the subscription life-cycle.

cc @taion 

> Aside from this, do you have any information on if and when this repo will be merged into relay official repo ? It would make sense !

This repo will not be merged into Relay Core. You can read more about why in [relay#1298](https://github.com/facebook/relay/pull/1298) and [relay#541](https://github.com/facebook/relay/issues/541).

**Comment by taion** [comment]
I think disposing a managed subscription would also probably be a bad idea – the container wouldn't have any idea whether that subscription got manually disposed or not, and the associated use case is enough of an edge case that I don't think it's worth explicitly supporting.

**Comment by yachaka** [comment]
Ok, sounds good to me.
I will reopen when I find a good example use-case.

Thanks for the replies 👍
