### ISSUE TITLE
Bump peer dependency range for Relay v0.10.x

### ISSUE THREAD

**Issue by taion** [edvinerikson/relay-subscriptions#23]
Currently the peer dep range requires 0.9.x.

I've actually moved all of my packages to use `>=` ranges instead of `^` ranges for Relay, but I'm not sure that's safe with Relay 2 coming soon... but then again it's better than having to remember to re-publish every time Relay bumps its version.

**Comment by edvinerikson** [comment]
1.0.1 is published now. let me know if you find any issues! Thanks for reporting

**Comment by taion** [comment]
Thanks!
