### ISSUE TITLE
Idea: Add helpers to intersect a query on the server to get relevant data

### ISSUE THREAD

**Issue by edvinerikson** [edvinerikson/relay-subscriptions#3]
``` js
type CommentCreateSubscriptionInput {
  clientMutationId: ID!
  storyId: ID!
}

subscription A($input_1: CommentCreateSubscriptionInput) {
  123Comment: commentCreateSubscription(input: $input_1) {
    commentEdge {
      cursor
      node
    }
  }
}
// When relay prints the query they rename the variables to input_1 input_2 etc. So we can't know for sure what pairs if we don't parse the query.
send(query, variables = { input_1: { clientMutationId: '1', storyId: '123' }});


// server
getVariablesForQuery(query, schema, {
  commentCreateSubscription: (arguments) => { // this will be called for the 123Comment field
    pubsub.subscribe(`comment_create_${arguments.input.storyId}`, sendPayloadToClient);
  }
});
```

What if we can intersect this query without executing it and get all variables paired with a subscription.
Then we can move the subscription creation from the resolve handlers on the server and still get rid of the separate topic that I send along the query in the todo app (create the topic server side instead of letting the client decide).

Does this make sense? I don't know..

**Comment by edvinerikson** [comment]
One way of doing this might be to create a helper like `mutationWithClientMutationId` that splits creation and resolving of subscriptions. Have a `createSubscription() {}` and `resolveSubsription() {}` method.

**Comment by nodkz** [comment]
I think that it should be solved via network layer. It has method `supports`. And may be (need search by relay sources), they check support network layer subscriptions or not. If not, throw warning if somebody try to create subscription.

**Comment by edvinerikson** [comment]
> I think that it should be solved via network layer. It has method supports. And may be (need search by relay sources), they check support network layer subscriptions or not. If not, throw warning if somebody try to create subscription.

I don't think we are talking about the same thing here, what I try to do here is to make it possible to use the subscription query itself to create a subscription on the server.

Right now the todo app works like this: I send a subscriptionId, topic, query and variables to the server, I would like it work like this: I send a query and variables to the server and execute it to create a subscription on the server. This is possible right now but it requires you to have all the creation logic in the resolve handlers and that can be a bit tedious if we want to get feedback from the graphql execution, e.g did the creation succeed? (possible but requires you to know the shape of the query). 

It would have been easy if we could just use the variables sent by the client as is but since we don't know the shape of them until we parse and pair them with a query, we can't.

However I'm not sure that the broader community will benefit from this, might be better to implement in the example app.

**Comment by nodkz** [comment]
Yep, I missed.

Anyway may be you didn't see talks about subscriptions, and can catch some good ideas: 
Standalone talk of Laney Kuenzel about subcriptions https://www.youtube.com/watch?v=mmke4w4gc6c
Talk with Lee on React Europe https://www.youtube.com/watch?v=ViXL0YQnioU

And of course, let ask @leebyron and @laneyk give some advice how to implement creation of subscriptions.

**Comment by taion** [comment]
I think https://github.com/edvinerikson/relay-subscriptions/pull/11 demonstrates this pattern with graphql-relay-subscription.

**Comment by edvinerikson** [comment]
:+1:
