### ISSUE TITLE
Error: Network request failed

### ISSUE THREAD

**Issue by pbassut** [edvinerikson/relay-subscriptions#32]
I'm getting this error when using library with [graphcool](http://graph.cool).
I suppose the problem is in the Environment because as soon as I remove it, things start to work again.

Here's how I inject the network layer: 
```
const environment = new RelaySubscriptions.Environment()
environment.injectNetworkLayer(new NetworkLayer(GRAPHQL_ENDPOINT, {
    get headers() {
        return {
            Authorization: 'Bearer XXX'
        }
    }
}))
```

My networkLayer is the same as the one in the README. Except that I'm passing the websocket url to socket.io:
```
export default class NetworkLayer extends Relay.DefaultNetworkLayer {
    constructor(...args) {
        super(...args);

        this.socket = io(GRAPHQL_ENDPOINT_WSS);
        this.requests = Object.create(null);

        this.socket.on('subscription update', ({ id, data, errors }) => {
            const request = this.requests[id];
            if (errors) {
                request.onError(errors);
            } else {
                request.onNext(data);
            }
        });
    }

    sendSubscription(request) {
        const id = request.getClientSubscriptionId();
        this.requests[id] = request;

        this.socket.emit('subscribe', {
            id,
            query: request.getQueryString(),
            variables: request.getVariables(),
        });

        return {
            dispose: () => {
                this.socket.emit('unsubscribe', id);
            },
        };
    }
}
```
This URL is in the form `wss://subscriptions.graph.cool/v1/__PROJECT_ID__`

And here's the tools version:

`"react-relay": "^0.10.0"`
`"relay-subscriptions": "^1.0.1"`
`"socket.io": "^2.0.1"`

Any idea of what might be going on?

**Comment by edvinerikson** [comment]
As far as I can tell graph.cool doesn't support socket.io so you need to use the browser default `WebSocket` api

**Comment by pbassut** [comment]
@edvinerikson Gotcha! But even if I remove the entire code from my networklayer it still gives me the "network failed" error. 
Maybe this have something to do with relay version?

**Comment by edvinerikson** [comment]
Not sure but it doesn't seem related to relay-subscriptions in that case. are you sure you pass in the correct api url?

**Comment by pbassut** [comment]
I am using the right URL.
After digging a little I noticed I'm getting a Bad request when trying to connect. 
That's probably because there's an initial handshake graphcool uses that conforms with the graphql spec.
I'm clueless. I'll try to use the apollo stack to accomplish this.

**Comment by edvinerikson** [comment]
I will close this is issue since it's not related to the library itself.
