### ISSUE TITLE
react-relay/classic usage?

### ISSUE THREAD

**Issue by voxmatt** [edvinerikson/relay-subscriptions#33]
Hey @edvinerikson, first, thanks for putting this together in the first place. We've been using it extensively for the last 6 months.

I was wondering if you have any thoughts on how to use this alongside relay 1.0. I'd love to be able to use it with relay/classic so that we can incrementally upgrade to relay-modern (using the relay-modern subscriptions requires moving to the relay-modern store, which requires upgrading everything at once).

I tried forking this bad-boy, upgrading to react-relay 1.0 and importing `react-relay/classic` instead of `react-relay`, but I can't seem to get it to work. I assume (although I don't _know_) that it's because the direct imports you have from `react-relay/lib...` now point to the relay-modern versions, but was curious if you had thoughts.

Thanks!

**Comment by taion** [comment]
I think that's the only thing, BTW – just need to update the imports here and cut a breaking release.

**Comment by edvinerikson** [comment]
Hello, thanks for raising the issue :)
I will not be able to do this myself until weekend but I will definitely be able to merge a PR if any of you send one. 😊

**Comment by voxmatt** [comment]
@edvinerikson I'll work on a PR, but my attempts so far have been failures (should be simple; not sure where I'm going wrong). So, if you still have time this weekend to take a stab, that would be much appreciated!

**Comment by edvinerikson** [comment]
The changes are published as `2.0.0`

Thanks for the help! :)

**Comment by voxmatt** [comment]
Woot! Thanks man!
