### ISSUE TITLE
Can not install relay-subscription

### ISSUE THREAD

**Issue by maituanmte** [edvinerikson/relay-subscriptions#36]
Hi all,
I install this module but I can't. It display an error 'invalid tar file'.
When I install todo example. It is a warning. but relay-subscription/lib folder is empty. Please help me to install it. Thanks

**Comment by taion** [comment]
@edvinerikson 

The latest publish seems to have an empty `lib/`: https://unpkg.com/relay-subscriptions@2.0.0/lib/

`npm build` populates `lib` as expected for me, so I think something went wrong in the publish

**Comment by edvinerikson** [comment]
Seems to work now. Thanks for notifying me :)
https://unpkg.com/relay-subscriptions@2.0.1/lib/

**Comment by maituanmte** [comment]
@taion 
I have a solution like that, I think it is helpful for you.

1. Go to node_modules folder, then clone this one from git to your node_modules: 
git clone https://github.com/edvinerikson/relay-subscriptions.git.
2. Go to relay-subscription folder: cd relay-subscriptions
3. npm install -> to install this module. It will install all dependencies and build its lib. 
4. remove react-relay in module: npm uninstall react-relay -> it can not work for many copies of react-relay.

Try it.
