### ISSUE TITLE
Move to relay-tools org?

### ISSUE THREAD

**Issue by alloy** [edvinerikson/relay-subscriptions#42]
This looks really useful!

Would you consider moving this to the https://github.com/relay-tools org so others can more easily find it? @taion can make it happen.

**Comment by edvinerikson** [comment]
That would certainly be interesting, although since Relay classic is near EOL not sure how much attention it should get in a somewhat near future.

**Comment by edvinerikson** [comment]
I guess it makes more sense having it on @relayjs

**Comment by alloy** [comment]
I’ve been finding lately that there’s still quite some people on Classic, but I see your point. FWIW I think that having a single org where community tooling around Relay can be found, regardless of Classic vs Modern, still helps in fostering a more engaged community.

**Comment by alloy** [comment]
The ‘relayjs’ org is just FB employees, whereas ‘relay-tools’ is not. If we can consolidate even more that would definitely have my preference, but not sure what all the considerations are.

@leebyron do you have any thoughts on that?

**Comment by edvinerikson** [comment]
I don't really have time maintaining this nor any use of this library. Perhaps moving it would be a good thing.

**Comment by sibelius** [comment]
I think we don't need this anymore on relay modern

**Comment by edvinerikson** [comment]
@sibelius It was mentioned above :)

**Comment by taion** [comment]
I might be willing to take this over. I think there's some value to the declarative approach for binding subscriptions to components, even with Relay Modern. @edvinerikson, what do you use these days?

**Comment by taion** [comment]
Specifically I'm talking about the `RelaySubscriptions.createContainer` API, rather than the internals around sending the subscriptions. We're still in the process of migrating fully to Relay Modern, but I would prefer to use a declarative API rather than using `requestSubscription` and `subscription.dispose()` directly and imperatively.

**Comment by edvinerikson** [comment]
I agree that a declarative api would be helpful, something that handles the start and end lifecycles of a subscription. Perhaps a React component like `QueryRenderer` but for subscriptions would work there.

**Comment by taion** [comment]
I suppose something like a `<Subscription>` component is more idiomatic these days than an HoC. But, yeah. I'd be happy to take over this repo and move toward building something like that out for Relay Modern.

**Comment by edvinerikson** [comment]
Great, perhaps I can transfer it to relay-tools?

**Comment by alloy** [comment]
Yup, that will automatically give @taion access too 👍

**Comment by taion** [comment]
I meant on npm too though :p

**Comment by edvinerikson** [comment]
I think I need to be a member of relay-tools to be able to transfer it. I will give access to npm as well

**Comment by alloy** [comment]
@edvinerikson Done

**Comment by edvinerikson** [comment]
Seems I need permission to create repos too

**Comment by edvinerikson** [comment]
Nvm, I had to manually join the org. Transfer in progress now

**Comment by edvinerikson** [comment]
Will see if I can figure out how npm works now

**Comment by edvinerikson** [comment]
I need a npm username @taion

**Comment by taion** [comment]
It's `taion` on npm as well. Thanks!

**Comment by edvinerikson** [comment]
I've added you now. I would encourage you enabling 2FA when publishing packages.

**Comment by alloy** [comment]
The main topic of this issue is definitely done by now 👍
