### ISSUE TITLE
regarding running the project

### ISSUE THREAD

**Issue by rajgaurav1989** [edvinerikson/relay-subscriptions#43]
Can you please mention the steps to run the project.

I tried :- 

1 ) cd relay-subscriptions/examples/todo
2) npm install
3) npm run update-schema
4) npm start

On running npm start it shows error attached in the screenshot . Please reply soon, I have to implement a project. Thanks in advance :)

![error](https://user-images.githubusercontent.com/14929684/44104608-e59aede6-a00c-11e8-84a6-adba58a73e94.png)

**Comment by rajgaurav1989** [comment]
@edvinerikson , please help me out , please tell me the steps to run your project. I have just started using relay and facing challenges in subscription. Please reach out , its very important.

**Comment by edvinerikson** [comment]
If you have just started using Relay, you should use Relay Modern.. this library is for Relay Classic (old version) and is not support for Relay Modern.
https://medium.com/@matt.krick/evented-subscriptions-in-relay-modern-9e04b14a82d8

**Comment by rajgaurav1989** [comment]
Thank you so much @edvinerikson
