### ISSUE TITLE
Other potential API updates

### ISSUE THREAD

**Issue by taion** [edvinerikson/relay-subscriptions#7]
Just some thoughts, to bring things more closely in line with https://github.com/facebook/relay/pull/1298:
- Add `subscribe` as a method on a subclass of `RelayEnvironment`, and optionally implement https://github.com/facebook/relay/issues/541#issuecomment-241137087 and add `RelaySubscriptions.createContainer` to make it available on `props.relay`
- ~~Delegate `subscribe` implementation to custom network layer rather than inject into `<SubscriptionProvider>`~~

**Comment by edvinerikson** [comment]
> add RelaySubscriptions.createContainer to make it available on props.relay

I am still not sure how that will be possible, do you have any small code-snippet that show it?

I like this, feels more integrated than the current API.
If you want to work on this, feel free to do so :+1:

**Comment by taion** [comment]
It'd essentially be

``` js
function createContainer(Component, config) {
  return Relay.createContainer(injectSubscribe(Component), config);
}
```

**Comment by edvinerikson** [comment]
👍🏼 but that would still make us use subscriptions.subscribe, right?

**Comment by taion** [comment]
I would actually make that call up to `context.relay.subscribe`, which would then delegate it to the network layer.

**Comment by edvinerikson** [comment]
Hmm I see.. if we inject our HOC inside the Relay HOC we can hijack the `props.relay` object a little..

**Comment by taion** [comment]
Yup exactly. It's one more HoC, but it saves having to make two separate wrapping HoC calls.

**Comment by edvinerikson** [comment]
Yeah, sounds like a plan

**Comment by taion** [comment]
2nd point in OP is handled in graphql-relay-subscription.
